library(httr)
library(jsonlite)
library(xml2)
library(tidyverse)


# Can use this to identify full raster name - which can be downloaded with API key
# should we get S3A AND S3B?
url1 <- "https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel3/search.json?maxRecords=100&productType=SY_2_V10___&platform=S3A" 
resp1 <- GET(url1)
out1 <- fromJSON(rawToChar(resp1$content))
out1$features$properties$title
out1$features$properties$services$download

# this is the Africa file from above
url <- "http://catalogue.dataspace.copernicus.eu/odata/v1/Products(a7b631b1-e6c4-549d-9beb-aa2b8244ba8c)/$value"
filename <- "example_odata.zip"
auth_header <- paste("Bearer", Sys.getenv("KEYCLOAK_TOKEN"), sep = " ")
response <- GET(url, add_headers(Authorization = auth_header), write_disk(filename, overwrite = TRUE))

url <- "https://catalogue.dataspace.copernicus.eu/odata/v1/Products"
resp <- GET(url)
out <- fromJSON(rawToChar(resp$content))
out$value$Id

# get token to downlaod products
# https://documentation.dataspace.copernicus.eu/#/APIs/OData


#######################################################
# prev. notes

# generated by following browser's search request
# this works but try to build cleaner request
url <-  "https://datahub.creodias.eu/odata/v1/Products?&$filter=(startswith(Name,%27S3%27)%20and%20(Attributes/OData.CSC.StringAttribute/any(att:att/Name%20eq%20%27instrumentShortName%27%20and%20att/OData.CSC.StringAttribute/Value%20eq%20%27SYNERGY%27)%20and%20Attributes/OData.CSC.StringAttribute/any(att:att/Name%20eq%20%27productType%27%20and%20att/OData.CSC.StringAttribute/Value%20eq%20%27SY_2_V10___%27)))%20and%20ContentDate/Start%20ge%202023-02-16T00:00:00.000Z%20and%20ContentDate/Start%20lt%202023-03-16T21:14:19.081Z%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;POLYGON%20((12.734528%205.181901,%2020.118713%205.181901,%2020.118713%2010.352748,%2012.734528%2010.352748,%2012.734528%205.181901))%27)&$orderby=ContentDate/Start%20desc&$expand=Attributes&$count=True&$top=50&$skip=0"
resp <- GET(url)
out <- fromJSON(rawToChar(resp$content))
names_to_download = out$value$Name

# these are example file names
# S3A_SY_2_V10____20230301T000000_20230310T235959_20230312T231426_AFRICA____________PS1_O_NT_002.SEN3
# S3B_SY_2_V10____20230301T000000_20230310T235959_20230313T143230_AFRICA____________PS2_O_NT_002.SEN3

# from open search https://documentation.dataspace.copernicus.eu/#/APIs/OpenSearch
url <-  "http://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel3/search.json?maxRecords=10"
resp <- GET(url)
out <- fromJSON(rawToChar(resp$content))
names_to_download = out$features$properties$title

# queryable params
url <- "https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel3/describe.xml"
# <parameters:Parameter name="name" value="{geo:name}" title="Location string e.g. Paris, France"/>
# <parameters:Parameter name="productType" value="{eo:productType}">
#   <parameters:Option value="SY_2_V10___"/>

# from template above
url <- "https://finder.creodias.eu/resto/api/collections/Sentinel3/search.json"

# from open search
url <- "https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel3/search.json?maxRecords=10&productType=SY_2_V10___&platform=S3A&box=13.4,7.46,24.0,23.4" 
# should we get S3B as well?
resp <- GET(url)
out <- fromJSON(rawToChar(resp$content))
gmlgeometry <- out$features$properties$title |> 
  filter(title == "S3A_SY_2_V10____20180922T111721_20181002T111721_20181012T115623_AFRICA____________LN2_O_NT_002.SEN3") 





