library(MODISTools)
library(tidyverse)
library(targets)
tar_load(bounding_boxes)
products <- mt_products()
MOD13Q1 <- products |> filter(product == "MOD13Q1")
bands <- mt_bands(product = "MOD13Q1")
ndvi <- bands |> filter(band == "250m_16_days_NDVI")
dates <- mt_dates(product = "MOD13Q1", lat = bounding_boxes$y_min[1], lon = bounding_boxes$x_max[1])
min(dates$calendar_date)
max(dates$calendar_date)
